name: Feature request
description: You have a cool new idea or an already fully baked mod you would like to be featured!
title: "*Coolest title ever*"
labels: Suggestion
body:
  - type: textarea
    attributes:
      label: What would you like to add?
      description: Here you can go into detail about what you want to add. 
      placeholder: Make a wizard do the dab because it's so trendy and would never be outdated ever.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How would you like this to be implemented? (optional)
      description: You can tell me how you would like me to make this if there is a preferred way.
      placeholder: Put on some sunglasses and do a dance!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional context (optional)
      description: Any other important context you may have for making this issue.
      placeholder: Accidental tiktok dance.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Type of suggestion
      description: Select which type of feature request you're submitting.
      options:
        - New Prodidows feature
        - New modpack
        - Something super awesome from a fork you play
        - Something you made by yourself
        - A new Prodidows version
        - Other
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: I agree to the following
      options:
        - label: By checking this box, I confirm that I haven't already made an issue about the topic being presented in this issue.
          required: true
        - label: By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.
          required: true
